// Generated by ChileQi JSON Class Generator
// QQ：1628983882

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TikTokTools.Util
{

    public class Author
    {

        [JsonProperty("avatar_larger")]
        public AvatarLarger AvatarLarger { get; set; }

        [JsonProperty("avatar_medium")]
        public AvatarMedium AvatarMedium { get; set; }

        [JsonProperty("avatar_thumb")]
        public AvatarThumb AvatarThumb { get; set; }

        [JsonProperty("aweme_count")]
        public int AwemeCount { get; set; }

        [JsonProperty("custom_verify")]
        public string CustomVerify { get; set; }

        [JsonProperty("enterprise_verify_reason")]
        public string EnterpriseVerifyReason { get; set; }

        [JsonProperty("favoriting_count")]
        public int FavoritingCount { get; set; }

        [JsonProperty("follow_status")]
        public int FollowStatus { get; set; }

        [JsonProperty("follower_count")]
        public int FollowerCount { get; set; }

        [JsonProperty("followers_detail")]
        public object FollowersDetail { get; set; }

        [JsonProperty("following_count")]
        public int FollowingCount { get; set; }

        [JsonProperty("geofencing")]
        public object Geofencing { get; set; }

        [JsonProperty("has_orders")]
        public bool HasOrders { get; set; }

        [JsonProperty("is_ad_fake")]
        public bool IsAdFake { get; set; }

        [JsonProperty("is_enterprise_vip")]
        public bool IsEnterpriseVip { get; set; }

        [JsonProperty("is_gov_media_vip")]
        public bool IsGovMediaVip { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("platform_sync_info")]
        public object PlatformSyncInfo { get; set; }

        [JsonProperty("policy_version")]
        public object PolicyVersion { get; set; }

        [JsonProperty("rate")]
        public int Rate { get; set; }

        [JsonProperty("region")]
        public string Region { get; set; }

        [JsonProperty("sec_uid")]
        public string SecUid { get; set; }

        [JsonProperty("secret")]
        public int Secret { get; set; }

        [JsonProperty("short_id")]
        public string ShortId { get; set; }

        [JsonProperty("signature")]
        public string Signature { get; set; }

        [JsonProperty("story_open")]
        public bool StoryOpen { get; set; }

        [JsonProperty("total_favorited")]
        public string TotalFavorited { get; set; }

        [JsonProperty("uid")]
        public string Uid { get; set; }

        [JsonProperty("unique_id")]
        public string UniqueId { get; set; }

        [JsonProperty("user_canceled")]
        public bool UserCanceled { get; set; }

        [JsonProperty("video_icon")]
        public VideoIcon VideoIcon { get; set; }

        [JsonProperty("with_commerce_entry")]
        public bool WithCommerceEntry { get; set; }

        [JsonProperty("with_fusion_shop_entry")]
        public bool WithFusionShopEntry { get; set; }

        [JsonProperty("with_shop_entry")]
        public bool WithShopEntry { get; set; }
    }

}
