// Generated by ChileQi JSON Class Generator
// QQ：1628983882

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TikTokTools.Util
{

    public class Aweme
    {

        [JsonProperty("author")]
        public Author Author { get; set; }

        [JsonProperty("aweme_id")]
        public string AwemeId { get; set; }

        [JsonProperty("aweme_type")]
        public int AwemeType { get; set; }

        [JsonProperty("cha_list")]
        public object ChaList { get; set; }

        [JsonProperty("comment_list")]
        public object CommentList { get; set; }

        [JsonProperty("desc")]
        public string Desc { get; set; }

        [JsonProperty("geofencing")]
        public object Geofencing { get; set; }

        [JsonProperty("image_infos")]
        public object ImageInfos { get; set; }

        [JsonProperty("label_top_text")]
        public object LabelTopText { get; set; }

        [JsonProperty("long_video")]
        public object LongVideo { get; set; }

        [JsonProperty("position")]
        public object Position { get; set; }

        [JsonProperty("promotions")]
        public object Promotions { get; set; }

        [JsonProperty("statistics")]
        public Statistics Statistics { get; set; }

        [JsonProperty("text_extra")]
        public IList<TextExtra> TextExtra { get; set; }

        [JsonProperty("uniqid_position")]
        public object UniqidPosition { get; set; }

        [JsonProperty("video")]
        public Video Video { get; set; }

        [JsonProperty("video_labels")]
        public object VideoLabels { get; set; }

        [JsonProperty("video_text")]
        public object VideoText { get; set; }
        
    }

}
