// Generated by ChileQi JSON Class Generator
// QQ：1628983882

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TikTokTools.Util
{

    public class Extra
    {

        [JsonProperty("logid")]
        public string Logid { get; set; }

        [JsonProperty("now")]
        public long Now { get; set; }
    }

}
