// Generated by ChileQi JSON Class Generator
// QQ：1628983882

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TikTokTools.Util
{

    public class Statistics
    {

        [JsonProperty("aweme_id")]
        public string AwemeId { get; set; }

        [JsonProperty("comment_count")]
        public int CommentCount { get; set; }

        [JsonProperty("digg_count")]
        public int DiggCount { get; set; }

        [JsonProperty("forward_count")]
        public int ForwardCount { get; set; }

        [JsonProperty("play_count")]
        public int PlayCount { get; set; }

        [JsonProperty("share_count")]
        public int ShareCount { get; set; }
    }

}
