// Generated by ChileQi JSON Class Generator
// QQ：1628983882

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TikTokTools.Util
{

    public class TextExtra
    {

        [JsonProperty("end")]
        public int End { get; set; }

        [JsonProperty("hashtag_id")]
        public object HashtagId { get; set; }

        [JsonProperty("hashtag_name")]
        public string HashtagName { get; set; }

        [JsonProperty("start")]
        public int Start { get; set; }

        [JsonProperty("type")]
        public int Type { get; set; }

        [JsonProperty("user_id")]
        public string UserId { get; set; }
    }

}
