// Generated by ChileQi JSON Class Generator
// QQ：1628983882

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TikTokTools.Util
{

    public class VideoIcon
    {

        [JsonProperty("uri")]
        public string Uri { get; set; }

        [JsonProperty("url_list")]
        public IList<object> UrlList { get; set; }
    }

}
