// Generated by ChileQi JSON Class Generator
// QQ：1628983882

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
namespace TikTokTools.Util
{

    public class Video
    {

        [JsonProperty("bit_rate")]
        public object BitRate { get; set; }

        [JsonProperty("cover")]
        public Cover Cover { get; set; }

        [JsonProperty("download_addr")]
        public DownloadAddr DownloadAddr { get; set; }

        [JsonProperty("duration")]
        public int Duration { get; set; }

        [JsonProperty("dynamic_cover")]
        public DynamicCover DynamicCover { get; set; }

        [JsonProperty("has_watermark")]
        public bool HasWatermark { get; set; }

        [JsonProperty("height")]
        public int Height { get; set; }

        [JsonProperty("origin_cover")]
        public OriginCover OriginCover { get; set; }

        [JsonProperty("play_addr")]
        public PlayAddr PlayAddr { get; set; }

        [JsonProperty("play_addr_lowbr")]
        public PlayAddrLowbr PlayAddrLowbr { get; set; }

        [JsonProperty("ratio")]
        public string Ratio { get; set; }

        [JsonProperty("vid")]
        public string Vid { get; set; }

        [JsonProperty("width")]
        public int Width { get; set; }
    }

}
